### ISSUE TITLE
Support multiple users owning the same NFT

### ISSUE THREAD

**Issue by kaitoo1** [gallery-so/gallery#5]
NFTs can belong to multiple users, but it looks like it can't in our system currently. Each NFT entry is unique by id and has only one associated user_id. So we have a situation for example where an nft is actually owned by five of our users, but the owner_id in our db is whoever set up/edited their gallery most recently or first(?).

**Comment by mikeydub** [comment]
Believe this is due to NFTs that are ERC1155.

Euler Beats is an example that we'll have to support. Early user @Graham has reported that his Euler Beat keeps getting removed from his Gallery (gallery.so/nfg) -- likely because another user must also the same type that has the same contract address and token id.

example:
https://opensea.io/assets/0x8754f54074400ce745a7ceddc928fb1b7e985ed6/559151581186
